services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "1234:5432"
  mailcatcher:
    container_name: "mailcatcher"
    image: "axllent/mailpit:latest"
    ports:
      - "1080:8025"
      - "1025:1025"
